Repository jfrog/jfrog-ide-webview, pull requests merged in 2023-12, with the labels that each got.

#52 Add verification code in SSO view
  package-lock.json
  package.json
  src/components/Page/Login/Login.test.tsx
  src/components/UI/CopyButton/CopyButton.module.css
  src/components/UI/CopyButton/CopyButton.tsx
  src/components/UI/Modal/pages/LoginModal.module.css
  src/components/UI/Modal/pages/LoginModal.test.tsx
  src/components/UI/Modal/pages/LoginModal.tsx
  src/components/UI/Progress/Progress.tsx
  src/components/UI/Progress/TimeoutProgress.test.tsx
  src/components/UI/Progress/TimeoutProgress.tsx
  src/model/login.ts
  src/model/webviewPages.ts
Labels: Improvement

#53 Init model pop-up window on close
  src/components/Page/Login/Login.tsx
Labels: bug

#54 Improve the verification code message
  src/components/UI/Modal/pages/LoginModal.test.tsx
  src/components/UI/Modal/pages/LoginModal.tsx
Labels: ignore for release

#55 Applying coding conventions
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/assets/icons/severity/critical.svg
  src/assets/icons/severity/high.svg
  src/assets/icons/severity/low.svg
  src/assets/icons/severity/medium.svg
  src/assets/icons/severity/unknown.svg
  src/assets/icons/undetermined.svg
  src/components/Page/Dependency/ApplicabilityEvidence.tsx
  src/components/Page/Sast/ContextualAnalysis.module.css
  src/components/Page/Sast/ContextualAnalysis.test.tsx
  src/components/Page/Sast/ContextualAnalysis.tsx
  src/components/Page/Sast/Research.module.css
  src/components/Page/Sast/Research.test.tsx
  src/components/Page/Sast/Research.tsx
  src/components/Page/Sast/Sast.module.css
  src/components/Page/Sast/Sast.test.tsx
  src/components/Page/Sast/Sast.tsx
  src/components/UI/Header/Header.tsx
  src/components/UI/InformationTabs/InformationTabs.module.css
  src/components/UI/InformationTabs/InformationTabs.test.tsx
  src/components/UI/InformationTabs/InformationTabs.tsx
  src/components/UI/InformationTabs/WhatCanIDoTab.test.tsx
  src/components/UI/InformationTabs/WhatCanIDoTab.tsx
  src/components/UI/InformationTabs/texts.ts
  src/components/UI/List/AnalysisStepsListElement.module.css
  src/components/UI/List/AnalysisStepsListElement.tsx
  src/components/UI/List/TimelineContent.tsx
  src/model/webviewPages.test.ts
  src/model/webviewPages.ts
  src/styles.ts
Labels: Improvement
